admin/app/dashboard/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from dashboard.views import *
from django.contrib.auth.views import login, logout


urlpatterns = patterns('',
    url(r'^$', login_required(index), name='index'),
    url(r'^settings', login_required(settings), name='settings'),
    url(r'^agents/(?P<id>.*)', login_required(agents), name='agents'),

    url(r'^task/add', login_required(add_task), name='add_task'),
    url(r'^task-file/add', login_required(add_task_file), name='add_task_file'),
    url(r'^task/(?P<id>.*)/edit/', login_required(edit_task), name='edit_task'),
    url(r'^task/(?P<id>.*)/delete/', login_required(delete_task), name='delete_task'),
    url(r'^task/(?P<id>.*)/info/', login_required(info_task), name='info_task'),
    url(r'^task', login_required(task), name='task'),

    url(r'^logs/(?P<id>.*)/delete/', login_required(delete_logs), name='delete_logs'),
    url(r'^logs/(?P<id>.*)/(?P<ids>.*)/', login_required(logs_view_list), name='logs_view_list'),
    url(r'^logs', login_required(logs), name='logs'),

    url(r'^files/(?P<id>.*)/delete/', login_required(delete_files), name='delete_files'),
    url(r'^files', login_required(files), name='files'),

)

admin/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from admin import settings

admin.autodiscover()

urlpatterns = patterns('',


    url(r'^', include('dashboard.urls')),
    url(r'^', include('core.urls')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),

    #(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
    #   'document_root': settings.MEDIA_ROOT}),


    #(r'^logs/(?P<path>.*)$', 'django.views.static.serve', {
    #    'document_root': settings.LOGS_ROOT})
)

admin/app/core/models.py
# -*- coding: utf-8 -*-
import base64
import datetime
import hashlib
import random
import time
from uuid import UUID
import uuid
from django.db import transaction
from django.contrib.auth.models import User, AbstractBaseUser
from django.core.files import File
from django.core.files.uploadedfile import SimpleUploadedFile
from django.db import models, connections, connection
from django.db.models import Q, F
from django.utils import timezone
from os.path import basename


def _createHash():
    hash = hashlib.sha1()
    hash.update(str(time.time()))
    return hash.hexdigest()[:41]


def _createUid():
    r_uuid = base64.urlsafe_b64encode(uuid.uuid4().bytes)
    return r_uuid.replace('=', '')[:30]


class SettingsUser(models.Model):
    user = models.OneToOneField(User)
    key = models.CharField(max_length=250, blank=True)
    value = models.CharField(max_length=250, blank=True)


class Agent(models.Model):
    type = models.IntegerField()  # тип агента
    uid = models.CharField(max_length=30, unique=True, default=0)
    country = models.CharField(max_length=2, blank=True)
    hostname = models.CharField(max_length=255, blank=True, null=True)
    ip = models.CharField(max_length=17, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return unicode(self.id)


    def get_or_create(self, uid, type_agent):
        agent, created = Agent.objects.get_or_create(uid=uid,type=type_agent, defaults={'uid': uid, 'type': type_agent})
        return agent

    def uid_generate(self, *args, **kwargs):
        self.uid = _createUid()
        super(Agent, self).save()

    class Meta:
        verbose_name = u"Agent"
        verbose_name_plural = u'Agents'



class Task(models.Model):
    TYPE_WHO = 0
    TYPE_REP = 1
    TYPE_LIST = 2
    TYPE_FILE = 3
    TYPE_FILEM = 4
    TYPE_RE = 5
    TYPE_RD = 6
    TYPE_EM = 7

    TYPE_CHOICES = (
        (TYPE_WHO, 'who'),
        (TYPE_REP, 'rep'),
        (TYPE_LIST, 'list'),
        (TYPE_FILE, 'file'),
        (TYPE_FILEM, 'filem'),
        (TYPE_RE, 're'),
        (TYPE_RD, 'rd'),
        (TYPE_EM, 'em'),
    )
    name = models.CharField(max_length=250)

    agent_type = models.CharField(max_length=255, blank=True)
    geo = models.CharField(max_length=255, blank=True)
    uids = models.CharField(max_length=1255, blank=True)

    type = models.IntegerField(choices=TYPE_CHOICES, blank=True, null=True)
    limit = models.IntegerField(blank=True, default=-1)
    all_limit = models.IntegerField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    data = models.CharField(max_length=255, blank=True, null=True, unique=True, default=0)


    def __unicode__(self):
        return unicode(self.id)

    def loaded(self):
        return Logs.objects.filter(task=self.id, status=0).count()

    def executed(self):
        return Logs.objects.filter(task=self.id, status=1).count()

    def result_limit(self):
        return self.loaded() + self.executed()

    @transaction.atomic()
    def save_custom(self, agent):
        Logs.objects.create(task=self, status=0, agent=agent, type=self.type)
        self.all_limit = self.result_limit()
        super(Task, self).save()
        return self


    @staticmethod
    def find_task(agent):
        try:
            task = Task.objects.filter((Q(geo='ALL') | Q(geo__iexact=agent.country)) &
                                   (Q(all_limit__gt=F('limit')) | Q(limit=-1)) &
                                   (Q(uids__icontains=agent.uid))).order_by('name')[0].save_custom(agent)
            return task
        except:
            pass

    class Meta:
        verbose_name = u"Task"
        verbose_name_plural = u'Task'





def make_upload_path(instance, filename):
    """Generates upload path for FileField"""
    return u"media/%s" % (filename)


class Files(models.Model):
    file = models.FileField(upload_to=make_upload_path, blank=True)
    agent = models.ForeignKey(Agent, related_name='files_agent', blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def name(self):
        return basename(self.file.name)

    @staticmethod
    def find_file(data):
        fls = Files.objects.get(file=data)
        print fls
        return fls

    def add(self, file, agent):
        try:
            myfile = SimpleUploadedFile(file.name, file.read())
            Files.objects.create(agent=agent, file=myfile)
            return True
        except:
            return False


def logs_upload_path(instance, filename):
    """Generates upload path for FileField"""
    return u"logs/%s/%s" % (instance.agent, filename)


class Logs(models.Model):
    STATUS_JOB = 0
    STATUS_ACTIVE = 1

    STATUS_CHOICES = (
        (STATUS_JOB, 'in the work'),
        (STATUS_ACTIVE, 'executed')
    )
    type = models.IntegerField(choices=Task.TYPE_CHOICES, blank=True, null=True)  # type task
    agent = models.ForeignKey(Agent, related_name='logs_agent')
    task = models.ForeignKey(Task, related_name='loaded_task', blank=True)
    status = models.IntegerField(choices=STATUS_CHOICES, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True, )
    file = models.FileField(upload_to=logs_upload_path, blank=True)

    def add(self, types, agent, data, task):
        try:
            name = str(types) + '_' + str(agent) + '_' + str(datetime.datetime.now().strftime("%d%m%Y_%I%M%S") + '.txt')
            myfile = SimpleUploadedFile(name, str(data))
            Logs.objects.filter(task=task).update(file=myfile)
            return True
        except:
            return False

    def display_text_file(self):
        return self.file.read()

admin/app/dashboard/forms.py
# -*- coding: utf-8 -*-
from django import forms
from core.models import *

class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        exclude = ['created', 'updated', 'all_limit', 'data']

    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'vTextField'
        #self.fields['agent_type'].widget.attrs['class'] = 'vIntegerField'
        self.fields['type'].widget.attrs['class'] = 'vIntegerField'
        #self.fields['uids'].widget.attrs['class'] = 'vIntegerField'
        self.fields['limit'].widget.attrs['class'] = 'vIntegerField'

class TaskFormFile(forms.ModelForm):

    class Meta:
        model = Task
        exclude = ['created', 'updated', 'all_limit', 'data']

    def __init__(self, *args, **kwargs):
        super(TaskFormFile, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'vTextField'
        #self.fields['agent_type'].widget.attrs['class'] = 'vIntegerField'
        self.fields['type'].widget.attrs['class'] = 'vIntegerField'
        self.fields['type'].widget.attrs['onmousedown'] = 'return false'
        #self.fields['type'].widget.attrs['disabled'] = ''
        self.fields['file_type'].widget.attrs['readonly'] = ''
        #self.fields['uids'].widget.attrs['class'] = 'vIntegerField'
        self.fields['limit'].widget.attrs['class'] = 'vIntegerField'

admin/app/dashboard/views.py
# -*- coding: utf-8 -*-
import base64
import datetime
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from core.models import *
from dashboard.forms import TaskForm, TaskFormFile


def index(request):
    context = RequestContext(request)
    agents = Agent.objects.all()
    context['agents'] = agents
    context['title'] = 'Home'
    context['active_menu'] = 'index'
    return render_to_response('index.html', context)


def task(request):
    context = RequestContext(request)

    context['tasks'] = Task.objects.all()
    context['title'] = 'Tasks'
    context['active_menu'] = 'Tasks'
    return render_to_response('task.html', context)


def logs(request):
    context = RequestContext(request)

    context['logs'] = Logs.objects.all()
    context['title'] = 'Logs'
    context['active_menu'] = 'Logs'
    return render_to_response('logs.html', context)

def files(request):
    context = RequestContext(request)

    context['files'] = Files.objects.all()
    context['title'] = 'Files'
    context['active_menu'] = 'Files'
    return render_to_response('files.html', context)

def settings(request):
    context = RequestContext(request)
    ruser = request.user
    settings = SettingsUser.objects.filter(user=ruser)

    if request.POST:
       num = request.POST.get('number')

       user = SettingsUser.objects.get(user=ruser.id)
       user.key = 'Number of items per page:'
       user.value = num
       user.save()

       context['title'] = 'Settings'
       context['user'] = ruser
       context['settings'] = settings
       context['active_menu'] = 'Settings'
    else:
       context['title'] = 'Settings'
       context['user'] = ruser
       context['settings'] = settings
       context['active_menu'] = 'Settings'
    return render_to_response('settings.html', context)

def agents(request, id=''):
    context = RequestContext(request)

    if id == '':
        return Http404

    agent = Agent.objects.get(id=id)

    context['result'] = agent
    context['task_history'] = Task.objects.filter(Q(uids__icontains=str(agent.id)))
    context['logs'] = agent.logs_agent
    context['files'] = agent.files_agent
    context['title'] = 'Agent | ' + str(agent.id)
    context['active_menu'] = 'Agents'
    return render_to_response('agents.html', context)

def logs_view_list(request, id="", ids=""):
    context = RequestContext(request)
    log = Logs.objects.get(id=id)

    context['files'] = log.agent.files_agent
    context['log'] = log
    context['title'] = 'Logs | List'
    context['active_menu'] = 'Logs'
    return render_to_response('logs-view-list.html', context)

def info_task(request, id=""):
    context = RequestContext(request)

    if id == '':
        return Http404
    tasks = Task.objects.get(id=id)

    loadeds = LoadedTask.objects.filter(task=tasks)

    context['title'] = 'Task info | ' + str(tasks.id)
    context['active_menu'] = 'Tasks'
    context['task'] = task
    context['loadeds'] = loadeds
    return render_to_response('info-task.html', context)

def edit_task(request, id=""):
    context = RequestContext(request)

    if id == '':
        return Http404

    task = Task.objects.get(id=id)

    context['fieldset'] = TaskForm(instance=task)

    if request.POST:
        task_form = TaskForm(request.POST, instance=task)
        print(task_form.errors)
        if task_form.is_valid():
            task = task_form.save(commit=False)
            task.updated = datetime.datetime.now()
            #task.data_generate()



            context['active_menu'] = 'Tasks'
            context['title'] = 'Edit Task'
            return HttpResponseRedirect('/task/')
        else:
            context['errors'] = True
            context['active_menu'] = 'Tasks'
            context['task'] = task
    else:
        context['active_menu'] = 'Tasks'
        context['title'] = 'Edit Task'
        context['task'] = task
    return render_to_response('edit-task.html', context)

def add_task(request):
    context = RequestContext(request)

    context['fieldset'] = TaskForm()

    if request.POST:
        task_form = TaskForm(request.POST)
        if task_form.is_valid():
            task = task_form.save(commit=False)
            task.all_limit = 0
            task.save()


            task.data_generate()
            task.save()


            return HttpResponseRedirect('/task/')
        else:
            context['errors'] = True
            context['active_menu'] = 'Tasks'
    else:
        context['active_menu'] = 'Tasks'
        context['title'] = 'Add Task'
    return render_to_response('add-task.html', context)

def add_task_file(request):
    context = RequestContext(request)
    ruser =request.user

    lister = ''
    for p in request.POST.getlist('files'):
            file = Files.objects.get(id=p)
            lister += str(file.file) + '\n'
    context['fieldset'] = TaskFormFile(initial={'file_type':lister, 'type':3})

    if request.POST.get('limit'):
        task_form = TaskFormFile(request.POST)
        if task_form.is_valid():
            task = task_form.save(commit=False)
            type = request.POST.get('type')
            task.type = type
            task.save()

            if request.POST.getlist('uids') == []:
                task.uids.clear()
                task.save()
            else:
               task.uids.clear()
               task.save()
               for project in request.POST.getlist('uids'):
                   task.uids.add(project)
                   task.save()


            return HttpResponseRedirect('/task/')
        else:
            context['errors'] = True
            context['active_menu'] = 'Tasks'
    else:
        context['active_menu'] = 'Tasks'
        context['title'] = 'Add Task'
    return render_to_response('add-task.html', context)

def delete_task(request, id=""):
    if id == '':
        return Http404

    task = Task.objects.get(id=id)
    task.delete()

    return HttpResponseRedirect('/task/')

def delete_logs(request, id=""):
    if id == '':
        return Http404

    logs = Logs.objects.get(id=id)
    logs.delete()

    return HttpResponseRedirect('/logs/')

def delete_files(request, id=""):
    if id == '':
        return Http404

    files = Files.objects.get(id=id)
    files.delete()

    return HttpResponseRedirect('/files/')

admin/app/dashboard/templates/add-task-file.html
{% extends 'base_dasboard.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
{% load grp_tags %}
{% spaceless %}
<form enctype="multipart/form-data" action="" method="post" id="task_form">{% csrf_token %}
 <fieldset class="grp-module {{ fieldset.classes }}">
        {% for line in fieldset %}
            {{ line }}
            {% if line.name == 'type' %}
                            v
            {% else %}
            <div class="grp-row grp-cells-1{% if errors %} grp-errors{% endif %}">
              {% for field in line %}
                <div class="l-2c-fluid l-d-4">
                            <div class="c-1">
                                <label class="required" for="{{ field.name }}">{{ field.name }}</label></div>
                            <div class="c-2">{{ field }}
                        </div>
                    </div>
              </div>

                  {% endfor %}{% endif %}


        {% endfor %}
    </fieldset>


<footer class="grp-module grp-submit-row grp-fixed-footer">
    <header style="display:none"><h1>Submit Options</h1></header>
    <ul>

        	<li><button type="submit" value="Save" class="grp-button grp-default" name="_continue">Save</button></li>
    </ul>
</footer>

</form>
{% endspaceless %}
{% endblock %}

admin/app/dashboard/templates/agents.html
{% extends 'base_dasboard.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}


<div class="grps-module">
<h2 class="custom_title">Agent info</h2>
        <table id="result_list_agent" cellspacing="0" class="grp-sortable">

            <tbody>
                    <tr class="grp-row grp-row-even %}">
                    <td>Uid</td>
                    <td>{{ result.uid }}</td>
                    </tr>

                    <tr class="grp-row grp-row-odd %}">
                    <td>Agent Type</td>
                    <td>{{ result.type }}</td>
                    </tr>

                    <tr class="grp-row grp-row-even %}">
                    <td>Ip</td>
                    <td>{{ result.ip }}</td>
                    </tr>

                    <tr class="grp-row grp-row-odd %}">
                    <td>Host</td>
                    <td>{{ result.hostname }}</td>
                    </tr>

                    <tr class="grp-row grp-row-even %}">
                    <td>Country</td>
                    <td>{{ result.country }}</td>
                    </tr>

                    <tr class="grp-row grp-row-odd %}">
                    <td>Created</td>
                    <td>{{ result.created|date:"j/n/Y H:i:s"  }}</td>
                    </tr>

                    <tr class="grp-row grp-row-even %}">
                    <td>Updated</td>
                    <td>{{ result.updated|date:"j/n/Y H:i:s" }}</td>
                    </tr>



            </tbody>
        </table>
    </div>

{% if task_history.all %}
<div class="grps-module">
<h2 class="custom_title">Task History</h2>

        <table id="result_list_agent" cellspacing="0" class="grp-sortable">
            <thead>
                <tr>
                        <th scope="col" >
                            <div class="grp-text"><span>Id</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>Name</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>Loaded</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>Executed</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>Created</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>Updated</span></div>
                        </th>
                </tr>
            </thead>
            <tbody>
                {% for result in task_history.all %}
                    <tr class="grp-row {% cycle 'grp-row-even' 'grp-row-odd' %}">
                    <td>{{ result.id }}</td>
                    <td>{{ result.name }}</td>
                    <td>{{ result.loaded }}</td>
                    <td>{{ result.executed }}</td>
                    <td>{{ result.created|date:"j/n/Y H:i:s" }}</td>
                    <td>{{ result.updated|date:"j/n/Y H:i:s" }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
</div>
{% else %}
{% endif %}


{% if logs.all  %}
<div class="grps-module">
<h2 class="custom_title">Logs</h2>

        <table id="result_list_agent" cellspacing="0" class="grp-sortable">
            <thead>
                <tr>
                        <th scope="col" >
                            <div class="grp-text"><span>Id</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>Type</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>Uid</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>Download</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>View</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>Created</span></div>
                        </th>
                </tr>
            </thead>
            <tbody>
                {% for result in logs.all %}
                    <tr class="grp-row {% cycle 'grp-row-even' 'grp-row-odd' %}">
                    <td>{{ result.id }}</td>
                    <td>{{ result.get_type_display }}</td>
                    <td>{{ result.agent }}</td>
                    <td><a href="/{{ result.file }}">Download</a></td>
                    <td>
                    {% if result.type == 2 %}<a href="{% url 'logs_view_list' result.id result.type  %}">View</a>
                    {% else %}
                    <a href="{% url 'logs_view_list' result.id result.type  %}">View</a>
                    {% endif %}
                    </td>
                    <td>{{ result.created|date:"j/n/Y H:i:s" }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
</div>
{% else %}
{% endif %}

{% if files.all  %}
<div class="grps-module">
<h2 class="custom_title">Files</h2>

        <table id="result_list_agent" cellspacing="0" class="grp-sortable">
            <thead>
                <tr>
                        <th scope="col" >
                            <div class="grp-text"><span>Id</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>Download Link</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>Uid</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>Name</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>Path</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>Size</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>Created</span></div>
                        </th>
                </tr>
            </thead>
            <tbody>
                {% for result in files.all %}
                    <tr class="grp-row {% cycle 'grp-row-even' 'grp-row-odd' %}">
                    <td>{{ result.id }}</td>
                    <td><a href="{{ result.file }}">Download</a></td>
                    <td>{{ result.agent }}</td>
                    <td>{{ result.name }}</td>
                    <td>{{ result.file }}</td>
                    <td>{{ result.file.size }}</td>
                    <td>{{ result.created|date:"j/n/Y H:i:s" }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
</div>
{% else %}
{% endif %}


{% endblock %}

admin/app/dashboard/templates/logs-view-list.html
{% extends 'base_dasboard.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}

<div>
<p>ID: {{ log.id }}</p><br>
<p>Type: {{ log.get_type_display }}</p><br>
<p>Uid: {{ log.agent }}</p><br>
<p>Created: {{ log.created|date:"j/n/Y H:i:s" }}</p><br>
{% if log.type == 2 %}
<div class="file_custom_osn">
<p>File list(Select the files to formulate the task):</p>
<form action="{% url 'add_task_file' %}" method="post" id="task_form">{% csrf_token %}
<div class="file_custom_list">
{% for file in files.all %}
    <div>
    <input type="checkbox" name="files" value="{{ file.id }}">
    <label>{{ file.name }}</label></div>
{% endfor %}
</div>
<button type="submit" value="Save" class="grp-button grp-default"  style="width: 50px;" name="_continue">Save</button>
</form>
</div>
{% else %}
<p>Text: <br>{{ log.display_text_file }}</p><br>

{% endif %}
</div>
{% endblock %}

admin/app/dashboard/templates/logs.html
{% extends 'base_dasboard.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
{% include  'pagination.html' with agent=logs %}
{% if logs %}
    <div class="grp-module grp-changelist-results">
        <table id="result_list" cellspacing="0" class="grp-sortable">
            <thead>
                <tr>
                        <th scope="col" >
                            <div class="grp-text"><span>Id</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>Type</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>Uid</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>Download</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>View</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>Created</span></div>
                        </th>
                        <th scope="col" >
                        </th>
                </tr>
            </thead>
            <tbody>
                {% for result in logs %}



                    <tr class="grp-row {% cycle 'grp-row-even' 'grp-row-odd' %}">
                    <td>{{ result.id }}</td>
                    <td>{{ result.get_type_display }}</td>
                    <td>{{ result.agent }}</td>
                    <td><a href="/{{ result.file }}">Download</a></td>
                    <td>
                    {% if result.type == 2 %}<a href="{% url 'logs_view_list' result.id result.type  %}">View</a>
                    {% else %}
                    <a href="{% url 'logs_view_list' result.id result.type  %}">View</a>
                    {% endif %}
                    </td>
                    <td>{{ result.created|date:"j/n/Y H:i:s" }}</td>
                    <td><a href="{% url 'delete_logs' result.id %}">Delete</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endif %}

{% endblock %}

admin/app/dashboard/templates/pagination.html
<div class="grp-module">
        <div class="grp-row">
            <div class="l-2cr-fluid ">
                    <div class="c-2">
<nav class="grp-pagination"><header style="display:none"><h1>Pagination</h1></header><ul><li class="grp-results"><span>{{ agent|length }} total</span></li></ul></nav>
                    </div>
            </div>
        </div>
 </div>

admin/app/dashboard/templates/settings.html
{% extends 'base_dasboard.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}

<form enctype="multipart/form-data" action="" method="post" id="task_form">{% csrf_token %}
    {% for setting in settings %}
<label>{{ setting.key }}</label>
    <input value="{{ setting.value }}" name="number"><br><br>
    {% endfor %}
<button type="submit" value="Save" class="grp-button grp-default"  style="width: 50px;" name="_continue">Save</button>
</form>
{% endblock %}

admin/app/dashboard/templates/task.html
{% extends 'base_dasboard.html' %}
{% block title %}{{ title }}{% endblock %}
{% block add_task %}
<ul class="grp-object-tools">
<li><a href="{% url 'add_task' %}" class="addlink">Add Task</a></li>
</ul>
{% endblock %}
{% block content %}
{% include  'pagination.html' with agent=tasks %}
{% if tasks %}
    <div class="grp-module grp-changelist-results">
        <table id="result_list" cellspacing="0" class="grp-sortable">
            <thead>
                <tr>
                        <th scope="col" >
                            <div class="grp-text"><span>Id</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>Name</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>Agent Type</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>Type</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>GEO</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>Uids</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>Loaded</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>Executed</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>Limit</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>Created</span></div>
                        </th>
                        <th scope="col" >
                            <div class="grp-text"><span>Updated</span></div>
                        </th>
                        <th scope="col" >
                        </th>
                        <th scope="col" >
                        </th>
                </tr>
            </thead>
            <tbody>
                {% for result in tasks %}
                    <tr class="grp-row {% cycle 'grp-row-even' 'grp-row-odd' %}">
                    <td>{{ result.id }}</td>
                    <td>{{ result.name }}</td>
                    <td>{{ result.agent_type }}</td>
                    <td>{{ result.get_type_display }}</td>
                    <td>{{ result.geo }}</td>
                    <td>{{ result.uids }}</td>
                    <td>{{ result.loaded }}</td>
                    <td>{{ result.executed }}</td>
                    <td>{{ result.limit }}</td>
                    <td>{{ result.created|date:"j/n/Y H:i:s" }}</td>
                    <td>{{ result.updated|date:"j/n/Y H:i:s" }}</td>
                    <td><a href="{% url 'edit_task' result.id %}">Edit</a></td>
                    <td><a href="{% url 'info_task' result.id %}">Info</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endif %}

{% endblock %}